# --- 1. IDENTITY SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        # Docker Compose'un oluşturduğu imaj ismi
        image: online-exam-system-identity-service:latest
        imagePullPolicy: Never  # <--- ÇOK ÖNEMLİ (Yerel imajı kullan)
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@db:5432/examdb" # 'db' servisine bağlan
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer # Localhost'tan erişmek için
  selector:
    app: identity-service
  ports:
    - port: 8000
      targetPort: 8000

# --- 2. EXAM SERVICE ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      containers:
      - name: exam-service
        image: online-exam-system-exam-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@db:5432/examdb"
---
apiVersion: v1
kind: Service
metadata:
  name: exam-service
spec:
  type: LoadBalancer
  selector:
    app: exam-service
  ports:
    - port: 8001      # Dışarıdan 8001 ile gireceğiz
      targetPort: 8000 # İçeride 8000 çalışıyor

# --- 3. SUBMIT SERVICE ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submit-service
  template:
    metadata:
      labels:
        app: submit-service
    spec:
      containers:
      - name: submit-service
        image: online-exam-system-submit-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: submit-service
spec:
  type: LoadBalancer
  selector:
    app: submit-service
  ports:
    - port: 8002      # Dışarıdan 8002 ile gireceğiz
      targetPort: 8000

# --- 4. GRADING SERVICE (WORKER) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-service
spec:
  replicas: 1 # İleride bunu arttırıp şov yapacağız!
  selector:
    matchLabels:
      app: grading-service
  template:
    metadata:
      labels:
        app: grading-service
    spec:
      containers:
      - name: grading-service
        image: online-exam-system-grading-service:latest
        imagePullPolicy: Never
        # Bu bir worker, port açmaya gerek yok.