name: CI/CD Pipeline

# Bu otomasyon ne zaman çalışsın?
on:
  push:
    branches: [ "main" ] # Ana kola kod atıldığında
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub'ın sanal sunucusunda çalış

    steps:
    # 1. Kodları Çek
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker Hub'a Giriş Yap
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. IDENTITY SERVICE - Build & Push
    - name: Build and Push Identity Service
      uses: docker/build-push-action@v4
      with:
        context: ./identity-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/online-exam-system-identity-service:latest

    # 4. EXAM SERVICE - Build & Push
    - name: Build and Push Exam Service
      uses: docker/build-push-action@v4
      with:
        context: ./exam-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/online-exam-system-exam-service:latest

    # 5. SUBMIT SERVICE - Build & Push
    - name: Build and Push Submit Service
      uses: docker/build-push-action@v4
      with:
        context: ./submit-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/online-exam-system-submit-service:latest

    # 6. GRADING SERVICE - Build & Push
    - name: Build and Push Grading Service
      uses: docker/build-push-action@v4
      with:
        context: ./grading-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/online-exam-system-grading-service:latest